### ISSUE TITLE
[GENERAL] Skull Face markings not showing

### ISSUE THREAD

**Issue by Sk0rpios** [TS-Rogue-Star/Rogue-Star#294]
#### Brief description of the bug
The Vulpkanin Skull Face and Unathi Skull Face body markings are not showing on characters. They are also not listed in the "Head and Face" section of the body markings.

#### What you expected to happen
The markings should be expected to show on characters.

#### What actually happened
The Unathi Skull Face marking has not been showing on a character that has had it previously, both in the character creator and in round. When I tried to apply it and the Vulpkanin Skull Face to a totally blank character with no features, it also did not show. Both times, the mark is applied in the body markings list but does not show any effect.

#### Steps to reproduce
- (Step 1): Open the character setup.
- (Step 2): Apply the Unathi Skull Face body marking or the Vulpkanin Skull Face body marking.
- (Step 3): Watch as it does not show on the character.

**Comment by ArgobargSoup** [comment]
I was going to write an issue report with some other missing markings before I noticed this here!  

I also found what's causing the issue... there's an extra "markings_alt.dmi" file that has the "missing" markings, along with a lot of duplicate markings from "markings_vr.dmi", and the corresponding entries for the "missing" markings are looking in the _vr file instead of the _alt file.

**Comment by Lilly-Lira** [comment]
This has been fixed! 

https://github.com/TS-Rogue-Star/Rogue-Star/pull/458
